version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    hostname : queue
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net
  datasvc:
    build: .
    hostname: dsvc
    ports:
      - 8080:8080
    networks:
      - rabbitmq_go_net
    depends_on:
      - rabbitmq
    restart: on-failure
networks:
  rabbitmq_go_net:
    driver: bridge
