version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    hostname: queue
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq/
    networks:
      - rabbitmq_go_net
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
  datasvc:
    build: .
    hostname: dsvc
    ports:
      - 8080:8080
    networks:
      - rabbitmq_go_net
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure
networks:
  rabbitmq_go_net:
    driver: bridge
volumes:
  rabbitmq_data:
  rabbitmq_log:
